/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author Merca Skole
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(service.CarFacadeREST.class);
        resources.add(service.AddressFacadeREST.class);
        resources.add(service.CartypeFacadeREST.class);
        resources.add(service.ReservationFacadeREST.class);
        resources.add(service.Member1FacadeREST.class);
        return resources;
    }
    
}
